# Used in production
# It adds the app and db to a new isolated network: backend

version: '3'

services:
  app:
    environment:
      DB_URL: "jdbc:postgresql://db:5432/listan"
    restart: unless-stopped
    networks:
      - backend
  db:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db-volume:
networks:
  backend:

