# Used in development
# It adds a default working DB_PASSWORD between the db and the app that can however be overriden
# It also exposes the port 9000 for easy access to the app locally

version: '3'

services:
  listan-server:
    environment:
      DB_PASSWORD: "${DB_PASSWORD:-password}"
      CRYPTO_SECRET: "${CRYPTO_SECRET:-G@m7wI=;NNpFx?1dHJQ7<dcN4Pw55xuhn0KN]:e?]Lr;]]DQsM7Sh;hY73EZpRZn}"
    ports:
      - "9000:9000"

  listan-mysql:
    environment:
      MYSQL_PASSWORD: "${DB_PASSWORD:-password}"

