version: 2
jobs:
  build:
    parallelism: 4
    working_directory: ~/listan-server
    docker:
      - image: codestar/circleci-scala-sbt-git:latest
        environment:
          - DB_URL="jdbc:postgresql://localhost:5432/listan"
          - DB_USER=ubuntu
      - image: postgres:9.5
        environment:
          - POSTGRES_USER=ubuntu
          - POSTGRES_DB=listan

    steps:
      - checkout

      - restore_cache:
          keys:
            - listan-server-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}
            - listan-server

      - run:
          # TODO: For some reason circleci gets stuck in the shell if we don't add exit to sbt
          command:
            sbt compile test:compile exit

      - save_cache:
          key: my-project-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}
          paths:
            - target/resolution-cache
            - target/streams
            - project/target/resolution-cache
            - project/target/streams
            - ~/.sbt
            - ~/.iv2/cache
            - ~/.m2
      - save_cache:
          # Changing this to a different key is the only way to remove old dependencies from the cache and/or generate a more up-to-date cache
          key: listan-server
          paths:
            - ~/.sbt
            - ~/.iv2/cache
            - ~/.m2

      - run:
          command:
            sbt test exit

      - store_test_results:
          path: target/test-reports
